apiVersion: v1
kind: Service
metadata:
  name: receiver
spec:
  selector:
    app: receiver
  ports:
    - port: 80
      protocol: TCP
      targetPort: receiver
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  name: receiver
  labels:
    app: receiver
spec:
  containers:
  - name: receiver
    image: quay.io/rvansa/eventing-hyperfoil-benchmark-vertx-receiver
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      protocol: TCP
      name: receiver
    env:
    - name: IO_HYPERFOIL_CONTROLLER_CLUSTER_IP
      value: hyperfoil-cluster.hyperfoil.svc.cluster.local
    - name: IO_HYPERFOIL_CONTROLLER_CLUSTER_PORT
      value: "7800"
