apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: receiver
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
    name: testchannel
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: receiver
