name: CI Hyperfoil Image build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          cache: 'maven'
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin' # Eclipse Temurin, the new home for AdoptOpenJDK
      - name: Build the Hyperfoil Receiver image
        run: cd vertx-receiver && mvn clean install
