name: CI Hyperfoil Image build and push

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '0 */12 * * 1-5'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          cache: 'maven'
          java-version: 17
          distribution: 'temurin' # Eclipse Temurin, the new home for AdoptOpenJDK
      - name: Build the Hyperfoil Receiver image
        run: cd vertx-receiver && mvn clean install
      - name: Push Images
        env:
          USER: ${{ secrets.QUAY_USER }}
          PASS: ${{ secrets.QUAY_TOKEN }}
        run: docker login -u "$USER" -p "$PASS" quay.io && docker push quay.io/openshift-knative/eventing-hyperfoil-benchmark-vertx-receiver
